services:
  web:
    user: "rails:rails"
    build: .
    ports:
      - "${PORT}:3000"
    environment:
      DATABASE_URL: "postgres://$DB_USERNAME:$DB_PASSWORD@$DB_ENDPOINT:$DB_PORT/$DB_NAME"
      RAILS_MASTER_KEY: "$RAILS_MASTER_KEY"
      SECRET_KEY_BASE: "$SECRET_KEY_BASE"
      RAILS_ENV: "$RAILS_ENV"