# REST Testing for Rails server


# SERVER STATUS
###

# Get status of server over localhost
GET http://{{LOCAL_HOST}}:{{APP_PORT}}/status

###

# Get status of server over local network
GET http://{{LOCAL_IP}}:{{APP_PORT}}/status

###

# Get status of server over Internet
GET http://{{PUBLIC_IP}}:{{APP_PORT}}/status


# LOGIN

###

# Submit username and password
POST http://{{PUBLIC_IP}}:{{APP_PORT}}/auth/login HTTP/1.1
content-type: application/json

{
    "username": "EXAMPLEUSERNAME",
    "password": "EXAMPLEPASSWORD"
}

# CREATE

###

# Submit request access form
POST http://{{PUBLIC_IP}}:{{APP_PORT}}/auth/create HTTP/1.1
content-type: application/json

{
    "newUsername": "TestUser",
    "newPassword": "assadasd",
    "confirmPassword": "assadasd",
    "firstName": "TestFirst",
    "lastName": "asd",
    "email": "exampleemail@gmail.com",
    "phoneNum": "1",
    "note": "Haa"
}